---
title: "analysis"
output: word_document
---
```{r}
setwd("~/kaggle")
small = read.csv("sm_train.csv", header=T, stringsAsFactors = F)
library(doMC)
registerDoMC()
set.seed(123)
```

```{r}
im.train = foreach(im = small$Image, .combine=rbind) %dopar% {
  as.integer(unlist(strsplit(im, " ")))
}
dim(im.train)
```

step 1. histogram stretching
```{r}
newdat = im.train

for (i in 1:nrow(im.train)){
  a = min(im.train[i,])
  b = max(im.train[i,])
  for (n in 1:ncol(im.train)){
    newdat[i,n] = (im.train[i,n]-a)/(b-a)*300}
}

range(newdat[2,])
```


compare the difference between stretched and unstretched images
```{r}
im1 <- matrix(data=rev(im.train[9,]), nrow=96, ncol=96) 
im2 <- matrix(data=rev(newdat[9,]), nrow=96, ncol=96)

# visualize the image
image(1:96, 1:96, im1, col=gray((0:255)/255))
image(1:96, 1:96, im2, col=gray((0:300)/300))
```


produce a test set first
```{r}
# use a test set 
train <- read.csv("training.csv", header=T, stringsAsFactors = F)

test = train[51:100,]

im.test = foreach(im = test$Image, .combine=rbind) %dopar% {
  as.integer(unlist(strsplit(im, " ")))
}
dim(im.test)

newtest = im.test

for (i in 1:nrow(im.test)){
  a = min(im.test[i,])
  b = max(im.test[i,])
  for (n in 1:ncol(im.test)){
    newtest[i,n] = (im.test[i,n]-a)/(b-a)*300}
}

range(newtest[2,])

truey = test[1:20,1]
```



step 2: PCR
```{r}
# the data frame we need
eyex = small$left_eye_center_x
newdat1 = data.frame(eyex, newdat)
dim(newdat1)

# conduct principle components regression
library(pls)
fit = pcr(eyex~., data=newdat1, scale=T, validation="CV")
summary(fit)

# 20 components explain approximately 90% of the variations in it
pcr.pred = predict(fit, newtest[1:20,], ncomp=20)
mean((pcr.pred-truey)^2)
```

now use ridge regression to predict left eye center y
```{r}
library(glmnet)
grid = 10^seq(10,-2, length=100)

eyey = small$left_eye_center_y
newdaty = data.frame(eyey, newdat)

ridge.mod = glmnet(newdat[1:50,], eyey, alpha=0, lambda=grid, thresh=1e-12)
ridge.pred = predict(ridge.mod, s=4, newx=newtest[1:20,])

lefty = test[1:20,2]
mean((ridge.pred-lefty)^2)
```


visualize our predictions
```{r}
# visualize the image
im <- matrix(data=rev(newdat[20,]), nrow=96, ncol=96)

image(1:96, 1:96, im, col=gray((0:300)/300))

# add some keypoints from the training data to check if everything is correct
points(96-small$left_eye_center_x[20], 96-small$left_eye_center_y[20], col="red")

# where are the left eye centers of each prediction we make
for(i in 1:20) {points(96-pcr.pred[i], 96-ridge.pred[i], col="red")}
```
